"""Change embedding size in Document

Revision ID: b796fcaa941b
Revises: 7c4f2b98e677
Create Date: 2024-12-06 05:55:10.085765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b796fcaa941b'
down_revision: Union[str, None] = '7c4f2b98e677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(dim=12000),
               type_=Vector,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedding',
               existing_type=Vector(dim=1560),
               type_=Vector(dim=12000),
               existing_nullable=True)
    # ### end Alembic commands ###
